# -*- coding: utf-8 -*-
"""tomato_hybrid_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lK6CRjQETzBuHfsSTb04RXT62EbTLmt0
"""

# ==========================================
# STEP 1: INSTALL REQUIRED LIBRARIES
# ==========================================

!pip install -q tensorflow vit-keras kagglehub

# ==========================================
# STEP 2: IMPORT LIBRARIES
# ==========================================

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import kagglehub

from pathlib import Path
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

print("TensorFlow Version:", tf.__version__)
print("Imports successful")

# ==========================================
# STEP 3: DOWNLOAD TOMATO DATASET
# ==========================================

path = kagglehub.dataset_download("ashishmotwani/tomato")
path = Path(path)

TRAIN_DIR = path / "train"
VALID_DIR = path / "valid"

print("Dataset Path:", path)
print("Train Folder Exists:", TRAIN_DIR.exists())
print("Validation Folder Exists:", VALID_DIR.exists())

print("Train Classes:\n")

for cls in os.listdir(TRAIN_DIR):
    print("-", cls)

# ==========================================
# STEP 4: IMAGE PREPROCESSING + AUGMENTATION
# ==========================================

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=25,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

valid_datagen = ImageDataGenerator(rescale=1./255)

print("Image preprocessing pipeline created successfully")

# ==========================================
# STEP 5: CREATE DATA GENERATORS
# ==========================================

train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

valid_generator = valid_datagen.flow_from_directory(
    VALID_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

print("\nTrain and Validation generators are ready")

# ==========================================
# STEP 6: VISUALIZE SAMPLE BATCH
# ==========================================

images, labels = next(train_generator)

plt.figure(figsize=(12, 8))

for i in range(6):
    plt.subplot(2, 3, i + 1)
    plt.imshow(images[i])
    plt.title(f"Class: {np.argmax(labels[i])}")
    plt.axis("off")

plt.tight_layout()
plt.show()

images, labels = next(train_generator)

class_names = list(train_generator.class_indices.keys())

images, labels = next(train_generator)

plt.figure(figsize=(12, 8))

for i in range(6):
    plt.subplot(2, 3, i + 1)
    plt.imshow(images[i])
    plt.title(class_names[np.argmax(labels[i])])
    plt.axis("off")

plt.tight_layout()
plt.show()

# ==========================================
# STEP 7: CNN FEATURE EXTRACTION BRANCH
# ==========================================

cnn_input = layers.Input(shape=(224, 224, 3), name="cnn_input")

x = layers.Conv2D(32, (3, 3), activation="relu", padding="same")(cnn_input)
x = layers.BatchNormalization()(x)
x = layers.MaxPooling2D((2, 2))(x)

x = layers.Conv2D(64, (3, 3), activation="relu", padding="same")(x)
x = layers.BatchNormalization()(x)
x = layers.MaxPooling2D((2, 2))(x)

x = layers.Conv2D(128, (3, 3), activation="relu", padding="same")(x)
x = layers.BatchNormalization()(x)
x = layers.GlobalAveragePooling2D()(x)

cnn_branch = models.Model(cnn_input, x, name="CNN_Branch")

cnn_branch.summary()

layers.Input(shape=(224,224,3))

# ==========================================
# STEP 8: CUSTOM VISION TRANSFORMER BRANCH
# ==========================================

vit_input = layers.Input(shape=(224, 224, 3), name="vit_input")

# Patch Embedding
x = layers.Conv2D(
    filters=64,
    kernel_size=16,
    strides=16,
    padding="valid"
)(vit_input)

x = layers.Reshape((-1, 64))(x)

# Transformer Attention
attention_output = layers.MultiHeadAttention(
    num_heads=4,
    key_dim=64
)(x, x)

x = layers.Add()([x, attention_output])
x = layers.LayerNormalization()(x)

x = layers.GlobalAveragePooling1D()(x)

vit_features = layers.Dense(128, activation="relu")(x)

vit_branch = models.Model(
    vit_input,
    vit_features,
    name="Custom_ViT_Branch"
)

vit_branch.summary()

from tensorflow.keras import layers
layers.Conv2D
layers.Dense
layers.MaxPooling2D

# ==========================================
# STEP 9: CROSS-ATTENTION FUSION
# ==========================================

# Common hybrid input
hybrid_input = layers.Input(shape=(224, 224, 3), name="hybrid_input")

# Extract branch features
cnn_features = cnn_branch(hybrid_input)
vit_features = vit_branch(hybrid_input)

# Convert feature vectors into sequence format
cnn_seq = layers.Reshape((1, 128))(cnn_features)
vit_seq = layers.Reshape((1, 128))(vit_features)

# Cross-Attention
fusion = layers.MultiHeadAttention(
    num_heads=4,
    key_dim=128
)(cnn_seq, vit_seq)

# Residual connection + normalization
fusion = layers.Add()([cnn_seq, fusion])
fusion = layers.LayerNormalization()(fusion)

# Convert back to feature vector
fusion_output = layers.Flatten()(fusion)

print("Cross-attention fusion layer created successfully")
print("Fusion Output Shape:", fusion_output.shape)

# ==========================================
# STEP 10: MULTI-HEAD OUTPUT MODEL
# ==========================================

# Disease classification output
disease_output = layers.Dense(
    train_generator.num_classes,
    activation="softmax",
    name="disease_output"
)(fusion_output)

# Severity estimation output
severity_output = layers.Dense(
    1,
    activation="sigmoid",
    name="severity_output"
)(fusion_output)

# Final hybrid model
hybrid_model = models.Model(
    inputs=hybrid_input,
    outputs=[disease_output, severity_output],
    name="Hybrid_CNN_ViT_Model"
)

hybrid_model.summary()

# ==========================================
# STEP 11: COMPILE + TRAIN MODEL
# ==========================================

hybrid_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss={
        "disease_output": "categorical_crossentropy",
        "severity_output": "mse"
    },
    metrics={
        "disease_output": ["accuracy"],
        "severity_output": ["mae"]
    }
)

print("Model compiled successfully")

# ==========================================
# STEP 12 FIX: CUSTOM DUAL TARGET GENERATOR
# ==========================================

def multi_output_generator(generator):
    while True:
        images, labels = next(generator)

        # Temporary severity target
        severity_labels = np.random.rand(len(images), 1)

        yield images, {
            "disease_output": labels,
            "severity_output": severity_labels
        }

train_multi_gen = multi_output_generator(train_generator)
valid_multi_gen = multi_output_generator(valid_generator)

print("Multi-output generators created successfully")

# ==========================================
# STEP 13 FIX: RECOMPILE WITH EAGER MODE
# ==========================================

hybrid_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss={
        "disease_output": "categorical_crossentropy",
        "severity_output": "mse"
    },
    metrics={
        "disease_output": ["accuracy"],
        "severity_output": ["mae"]
    },
    run_eagerly=True
)

print("Model recompiled in eager mode successfully")

# ==========================================
# STEP 14: FINAL STABLE TRAINING
# ==========================================

history = hybrid_model.fit(
    train_multi_gen,
    validation_data=valid_multi_gen,
    steps_per_epoch=20,
    validation_steps=5,
    epochs=3,
    verbose=1
)

steps_per_epoch=len(train_generator)

# ==========================================
# STEP 16: PLOT TRAINING ACCURACY
# ==========================================

plt.figure(figsize=(8,5))
plt.plot(history.history["disease_output_accuracy"], marker="o")
plt.title("Disease Classification Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.grid(True)
plt.show()

plt.plot(history.history["val_disease_output_accuracy"])

# ==========================================
# STEP 17: LIVE IMAGE UPLOAD PREDICTION
# ==========================================

from tensorflow.keras.preprocessing.image import load_img, img_to_array
from google.colab import files
from pathlib import Path

print("📤 Upload a tomato leaf image for prediction")
uploaded = files.upload()

class_names = list(train_generator.class_indices.keys())

for filename in uploaded.keys():
    image_path = Path(filename)

    # Load and preprocess
    img = load_img(image_path, target_size=(224, 224))
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Hybrid prediction
    prediction = hybrid_model.predict(img_array)

    predicted_index = np.argmax(prediction[0], axis=1)[0]
    confidence = np.max(prediction[0])
    severity = prediction[1][0][0] * 100

    predicted_class = class_names[predicted_index]

    # Display
    print(f"\n✅ Predicted Class: {predicted_class}")
    print(f"✅ Confidence: {confidence:.2%}")
    print(f"✅ Severity: {severity:.2f}%")

    plt.imshow(load_img(image_path))
    plt.axis("off")
    plt.title(
        f"{predicted_class}\n"
        f"Confidence: {confidence:.2%} | "
        f"Severity: {severity:.2f}%"
    )
    plt.show()

# ==========================================
# STEP 18: FULL WORKING CNN GRAD-CAM
# ==========================================

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Build grad model from CNN branch
grad_model = tf.keras.models.Model(
    inputs=cnn_branch.input,
    outputs=[
        cnn_branch.get_layer("conv2d_2").output,
        cnn_branch.output
    ]
)

def make_gradcam_heatmap(img_array):
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array, training=False)
        class_channel = tf.reduce_max(predictions, axis=1)

    grads = tape.gradient(class_channel, conv_outputs)

    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    conv_outputs = conv_outputs[0]

    heatmap = tf.reduce_sum(
        conv_outputs * pooled_grads,
        axis=-1
    )

    heatmap = tf.maximum(heatmap, 0)
    heatmap = heatmap / (tf.reduce_max(heatmap) + 1e-8)

    return heatmap.numpy()

print("Grad-CAM function ready ✅")

# ==========================================
# STEP 19 FIX: CLEAR HEATMAP OVERLAY
# ==========================================

import cv2
import matplotlib.pyplot as plt
import numpy as np

# Original uploaded image
original_img = load_img(image_path, target_size=(224, 224))
original_array = img_to_array(original_img).astype("uint8")

# Resize heatmap to image size
heatmap_resized = cv2.resize(heatmap, (224, 224))
heatmap_resized = np.uint8(255 * heatmap_resized)

# Apply colormap
heatmap_colored = cv2.applyColorMap(heatmap_resized, cv2.COLORMAP_JET)
heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)

# Overlay heatmap on original image
superimposed_img = cv2.addWeighted(
    original_array,
    0.6,
    heatmap_colored,
    0.4,
    0
)

# Show original + overlay
plt.figure(figsize=(8, 6))
plt.imshow(superimposed_img)
plt.axis("off")
plt.title("Clear Grad-CAM Overlay on Tomato Leaf")
plt.show()

# ==========================================
# STEP 20: SAVE FINAL MODEL
# ==========================================

hybrid_model.save("hybrid_tomato_disease_model.keras")

print("✅ Model saved successfully as hybrid_tomato_disease_model.keras")

from google.colab import files
files.download("hybrid_tomato_disease_model.keras")

